"""Create authentication table

Revision ID: 39c9a96d5de0
Revises: 1ab35b02558f
Create Date: 2024-08-10 23:08:13.860018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '39c9a96d5de0'
down_revision: Union[str, None] = '1ab35b02558f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('authentications',
    sa.Column('token', sa.String(), nullable=False, primary_key=True, index=True),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authentications')
    # ### end Alembic commands ###
