"""Create user_detail table

Revision ID: 51233f56e1f2
Revises: 39c9a96d5de0
Create Date: 2024-08-11 00:48:45.976763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51233f56e1f2'
down_revision: Union[str, None] = '39c9a96d5de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('artists', 
        sa.Column('id', sa.UUID(as_uuid=True), primary_key=True, nullable=False,),
        sa.Column('name', sa.VARCHAR(length=255), nullable=False, unique=True, index=True),
    )

    op.create_table('playlists', 
        sa.Column('id', sa.UUID(as_uuid=True), primary_key=True, nullable=False,),
        sa.Column('user_id', sa.UUID(as_uuid=True), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
    )

    op.create_table('songs', 
        sa.Column('id', sa.UUID(as_uuid=True), primary_key=True, nullable=False,),
        sa.Column('name', sa.VARCHAR(length=255), nullable=False, index=True),
        sa.Column('link', sa.VARCHAR(length=255), nullable=False, unique=True),
    )

    op.create_table('song_artists', 
        sa.Column('id', sa.UUID(as_uuid=True), primary_key=True, nullable=False,),
        sa.Column('artist_id', sa.UUID(as_uuid=True), sa.ForeignKey('artists.id', ondelete='CASCADE'), nullable=False),
        sa.Column('song_id', sa.UUID(as_uuid=True), sa.ForeignKey('songs.id', ondelete='CASCADE'), nullable=False),
    )

    op.create_table('song_playlists',
        sa.Column('id', sa.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('playlist_id', sa.UUID(as_uuid=True), sa.ForeignKey('playlists.id', ondelete='CASCADE'), nullable=False),
        sa.Column('song_id', sa.UUID(as_uuid=True), sa.ForeignKey('songs.id', ondelete='CASCADE'), nullable=False),
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_details',
        sa.Column('id', sa.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('user_id', sa.UUID(as_uuid=True), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('myanimelist', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_details')
    op.drop_table('song_artists')
    op.drop_table('song_playlists')
    op.drop_table('artists')
    op.drop_table('playlists')
    op.drop_table('songs')
    # ### end Alembic commands ###
